repositories:
  remote:
   - http://repo1.maven.org/maven2
   - http://download.eclipse.org/rt/eclipselink/maven.repo
   - http://repository.codehaus.org

artifacts:
  eclipselink: org.eclipse.persistence:eclipselink:jar:2.3.0
  postgresql: postgresql:postgresql:jar:9.1-901.jdbc4
  postgis_jdbc: org.postgis:postgis-jdbc:jar:1.3.3
  #postgis_jdbc: org.postgis:postgis-jdbc:jar:2.0.2SVN
  javax_persistence: org.hibernate.javax.persistence:hibernate-jpa-2.0-api:jar:1.0.0.Final
  javax_validation: javax.validation:validation-api:jar:1.0.0.GA
  javax_transaction: javax.transaction:jta:jar:1.1
  jtds: net.sourceforge.jtds:jtds:jar:1.2.4
  ejb_api: org.apache.geronimo.specs:geronimo-ejb_3.1_spec:jar:1.0.2
  javaee_api: javax:javaee-api:jar:6.0
  javax_annotation: com.google.code.findbugs:jsr305:jar:1.3.9
  json: org.json:json:jar:20090211
  jackson_core: org.codehaus.jackson:jackson-core-asl:jar:1.9.4
  jackson_mapper: org.codehaus.jackson:jackson-mapper-asl:jar:1.9.4
  javax_validation: javax.validation:validation-api:jar:1.0.0.GA

  slf4j_api: org.slf4j:slf4j-api:jar:1.6.6
  slf4j_jdk14: org.slf4j:slf4j-jdk14:jar:1.6.6
  infomas_annotation_detector: eu.infomas:annotation-detector:jar:3.0.0

  geolatte_common: org.geolatte:geolatte-common:jar:0.5

  geolatte_geom: org.geolatte:geolatte-geom:jar:0.12-rf
  jts: com.vividsolutions:jts:jar:1.10
