repositories:
  remote:
   - http://repo1.maven.org/maven2
   - http://repository.codehaus.org
   - http://maven.vaadin.com/vaadin-addons

artifacts:
  javax_javaee: javax:javaee-api:jar:7.0
  javax_javaee_endorsed: javax:javaee-endorsed-api:jar:7.0

  findbugs_annotations: com.google.code.findbugs:annotations:jar:2.0.1
  javax_jsr305: com.google.code.findbugs:jsr305:jar:1.3.9
  javax_inject: javax.inject:javax.inject:jar:1

  infomas_annotation_detector: eu.infomas:annotation-detector:jar:3.0.0

  javax_json: org.glassfish:javax.json:jar:1.0.3

  # GWT Dependencies
  gwt_user: com.google.gwt:gwt-user:jar:2.6.1
  gwt_dev: com.google.gwt:gwt-dev:jar:2.6.1
  gwt_gin: com.google.gwt.inject:gin:jar:2.1.2
  javax_validation: javax.validation:validation-api:jar:1.0.0.GA
  javax_validation_sources: javax.validation:validation-api:jar:sources:1.0.0.GA

  # Jackson Dependencies
  jackson_core: org.codehaus.jackson:jackson-core-asl:jar:1.9.13
  jackson_mapper: org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13

  google_guice: com.google.inject:guice:jar:3.0
  google_guice_assistedinject: com.google.inject.extensions:guice-assistedinject:jar:3.0
  aopalliance: aopalliance:aopalliance:jar:1.0 # Required for guice

  jeo: org.realityforge.jeo:jeo:jar:0.5

  geolatte_geom: org.geolatte:geolatte-geom:jar:0.13
  jts: com.vividsolutions:jts:jar:1.13
  slf4j_api: org.slf4j:slf4j-api:jar:1.6.6
  slf4j_jdk14: org.slf4j:slf4j-jdk14:jar:1.6.6

  rest_field_filter: org.realityforge.rest.field_filter:rest-field-filter:jar:0.4

  geolatte_geom_jpa: org.realityforge.geolatte.jpa:geolatte-geom-jpa:jar:0.1

  gwt_appcache_client: org.realityforge.gwt.appcache:gwt-appcache-client:jar:1.0.4
  gwt_appcache_linker: org.realityforge.gwt.appcache:gwt-appcache-linker:jar:1.0.4
  gwt_appcache_server: org.realityforge.gwt.appcache:gwt-appcache-server:jar:1.0.4

  gwt_cache_filter: org.realityforge.gwt.cache-filter:gwt-cache-filter:jar:0.3

  g_leaflet_draw: org.peimari:g-leaflet-draw:jar:0.4.0
  g_leaflet: org.peimari:g-leaflet:jar:0.4.0
